/*
 * Copyright (C) 2018 NATSRL @ UMD (University Minnesota Duluth)
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package common.route;

import common.infra.Corridor;
import common.infra.Infra;
import common.ui.map.MapHelper;
import common.pyticas.LocalRouteClient;
import common.ui.map.TileServerFactory;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chongmyung Park
 */
public class RouteListPanel extends JPanel implements IRouteChanged {

    
    protected List<Corridor> corridors = new ArrayList<>();
    protected Route selectedRoute;
    protected MapHelper mapHelper;

    /**
     * Creates new form RouteEditorPanel
     */
    public RouteListPanel() {
        initComponents();
        this.jxMap.setTileFactory(TileServerFactory.getTileFactory());
    }

    public void init() {
        Infra infra = Infra.getInstance();
        this.corridors = infra.getCorridors();
        
        this.jxMap.getMiniMap().setVisible(false);
        this.mapHelper = new MapHelper(jxMap);
        
        // add click-event handler for a route list
        this.tbRouteList.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = tbRouteList.rowAtPoint(e.getPoint());
                DefaultTableModel tm = (DefaultTableModel) tbRouteList.getModel();
                Route s = (Route) tm.getValueAt(row, 0);
                setProperties(s);
            }
        });
        
        LocalRouteClient.getInstance().addChangeListener(this);
        LocalRouteClient.getInstance().loadList();               
    }

    protected void setProperties(Route s) {
        this.mapHelper.showRoute(s);
        this.mapHelper.setCenter(s.getRNodes().get(0));
        this.selectedRoute = s;
    }

    @Override
    public void routeChanged(List<Route> routeList) {
        if (this.tbRouteList == null) {
            return;
        }
        final DefaultTableModel tm = (DefaultTableModel) this.tbRouteList.getModel();
        tm.getDataVector().removeAllElements();
        tm.fireTableDataChanged();
        for (Route s : routeList) {
            tm.addRow(new Object[]{s, s.desc, "Delete"});
        }
        if (routeList.size() > 0) {
            Route s = (Route) tm.getValueAt(0, 0);
            if (s != null) {
                setProperties(s);
            }
        }
    }

    protected void deleteRoute() {
        if (this.selectedRoute == null) {
            return;
        }
        int res = JOptionPane.showConfirmDialog(this, "Delete this route?", "Confirm", JOptionPane.YES_NO_OPTION);

        if (res == JOptionPane.YES_OPTION) {
            LocalRouteClient.getInstance().deleteRoute(this.selectedRoute);
            this.selectedRoute = null;
            LocalRouteClient.getInstance().loadList();
        }
    }

    protected void saveRouteConfig(Route r) {
        RouteLaneConfigDialog rlcd = new RouteLaneConfigDialog(r, null, true);
        rlcd.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        asyncRequestAdapter1 = new org.jdesktop.http.async.event.AsyncRequestAdapter();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbRouteList = new javax.swing.JTable();
        btnDeleteSelection = new javax.swing.JButton();
        btnSetLaneConfig = new javax.swing.JButton();
        jxMap = new org.jdesktop.swingx.JXMapKit();

        jLabel2.setText("Routes");

        tbRouteList.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        tbRouteList.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ));
        jScrollPane3.setViewportView(tbRouteList);

        btnDeleteSelection.setText("Delete");
        btnDeleteSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSelectionActionPerformed(evt);
            }
        });

        btnSetLaneConfig.setText("Set Lane Configs");
        btnSetLaneConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetLaneConfigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDeleteSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSetLaneConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jxMap, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDeleteSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSetLaneConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jxMap, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))
                .addContainerGap())
        );
    }private void btnDeleteSelectionActionPerformed(java.awt.event.ActionEvent evt) {
            this.deleteRoute();
        }

    private void btnSetLaneConfigActionPerformed(java.awt.event.ActionEvent evt) {
        if (this.selectedRoute != null) {
            this.saveRouteConfig(this.selectedRoute);
        }
    }


    // Variables declaration - do not modify
    private org.jdesktop.http.async.event.AsyncRequestAdapter asyncRequestAdapter1;
    private javax.swing.JButton btnDeleteSelection;
    private javax.swing.JButton btnSetLaneConfig;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private org.jdesktop.swingx.JXMapKit jxMap;
    private javax.swing.JTable tbRouteList;
    // End of variables declaration

}
