/*
 * Copyright (C) 2018 NATSRL @ UMD (University Minnesota Duluth)
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package common.route;

import common.infra.RNode;
import common.pyticas.LocalRouteClient;

import java.awt.Frame;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Chongmyung Park
 */
public class RouteSaveDialog extends javax.swing.JDialog {

    public boolean isSaved = false;
    private List<RNode> rnodes;
    private final LocalRouteClient routeApi;

    /**
     *
     * @param parent
     * @param rnodes
     */
    public RouteSaveDialog(Frame parent, List<RNode> rnodes, LocalRouteClient routeApi) {
        super(parent, true);
        initComponents();
        this.rnodes = rnodes;
        this.routeApi = routeApi;
    }

    private void saveRoute() {
        String name = this.tbxRouteName.getText();
        String desc = this.tbxRouteDesc.getText();
        if (!checkName(name)) {
            return;
        }
        Route r = new Route(name, desc);
        for (RNode rn : this.rnodes) {
            r.addRNode(rn);
        }
        isSaved = LocalRouteClient.getInstance().saveRoute(r);
        if (isSaved) {
            routeApi.loadList();
            dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, String.format("Fail to save route"));
        }
    }

    private boolean checkName(String name) {
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Fail : Route name is required");
            return false;
        }
        if (name.length() > 128) {
            JOptionPane.showMessageDialog(rootPane, "Fail : Route name is long. (128 characters limit)");
            return false;
        }
        String eName = Route.getFileName(name);
        if (eName == null) {
            JOptionPane.showMessageDialog(rootPane, "Fail : MD5 algorithm does not exist!!");
            return false;
        }
        Route exRoute = routeApi.getRoute(name);
        if (exRoute != null) {
            int res = JOptionPane.showConfirmDialog(rootPane, "Route name already exists. Overwrite the route?");
            if (res > 0) {
                return false;
            }
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tbxRouteName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbxRouteDesc = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Save");

        jLabel2.setText("Route Name");

        jLabel3.setText("Description");

        tbxRouteDesc.setColumns(20);
        tbxRouteDesc.setRows(5);
        jScrollPane1.setViewportView(tbxRouteDesc);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(tbxRouteName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbxRouteName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        saveRoute();
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tbxRouteDesc;
    private javax.swing.JTextField tbxRouteName;
    // End of variables declaration

}
