/*
 * Copyright (C) 2018 NATSRL @ UMD (University Minnesota Duluth)
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package common.ui.map;

import org.jdesktop.swingx.mapviewer.GeoPosition;
import common.config.Config;

/**
 *
 * @author Chongmyung Park <chongmyung.park@gmail.com>
 */
public class MapPanel extends javax.swing.JPanel {

    private final int initZoom = 10;
    private final double initLatitude = 44.974878;
    private final double initLongitude = -93.233414;    
    public MapHelper mapHelper;
    
    /**
     * Creates new form MapPanel
     */
    public MapPanel() {
        initComponents();   
        //this.jmKit.setDefaultProvider(MapProvider.TMC.getProvider());   
        this.jmKit.setTileFactory(Config.getMapProvider().getProvider().getTileFactory());
        this.jmKit.setAddressLocation(new GeoPosition(this.initLatitude, this.initLongitude));
        this.jmKit.setZoom(this.initZoom);
        this.jmKit.getMiniMap().setVisible(false);           
    }
    
    public void init() {               
        this.mapHelper = new MapHelper(this.jmKit);
        this.jmKit.getMiniMap().setVisible(false);     
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jmKit = new org.jdesktop.swingx.JXMapKit();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jmKit, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jmKit, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );
    }// Variables declaration - do not modify
    private org.jdesktop.swingx.JXMapKit jmKit;
    // End of variables declaration
}
