/*
 * Copyright (C) 2018 NATSRL @ UMD (University Minnesota Duluth)
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ticas.ncrtes;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import ticas.common.ui.IInitializable;

/**
 *
 * @author Chongmyung Park <chongmyung.park@gmail.com>
 */
public class NCRTESPanel extends javax.swing.JPanel implements IInitializable {

    private List<Integer> initializedTabs = new ArrayList<Integer>();

    /**
     * Creates new form NCRTMain
     */
    public NCRTESPanel() {
        initComponents();
    }

    public NCRTESPanel(JFrame mainFrame) {
        initComponents();
        NCRTESConfig.mainFrame = mainFrame;
    }

    @Override
    public void init() {        
        NCRTESInfoLoader.getInstance().init(new NCRTESInfoLoader.ICallback() {
            @Override
            public void ready() {
                ChangeListener changeListener = new ChangeListener() {
                    @Override
                    public void stateChanged(ChangeEvent changeEvent) {
                        Integer idx = mainTab.getSelectedIndex();
                        if (initializedTabs.contains(idx)) {
                            return;
                        }
                        initializedTabs.add(idx);
                        IInitializable tab = (IInitializable) mainTab.getSelectedComponent();
                        tab.init();
                    }
                };
                mainTab.addChangeListener(changeListener);      
                mainTab.setSelectedIndex(0);
                panEstimation.init();             
            }

            @Override
            public void fail() {
                JOptionPane.showMessageDialog(null, "Fail to connect to NCRTES server");
            }
        });   
    }
    
    @Override
    public void refresh() {
        // do nothing
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTab = new javax.swing.JTabbedPane();
        panEstimation = new ticas.ncrtes.estimation.EstimationUI();
        sNRouteConfigPanel2 = new ticas.ncrtes.snowroute.SNRouteConfigPanel();
        targetLaneUI1 = new ticas.ncrtes.targetstation.TargetStationUI();

        mainTab.addTab("Estimation", panEstimation);
        mainTab.addTab("Truck Route", sNRouteConfigPanel2);
        mainTab.addTab("Lane Configurations", targetLaneUI1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTab, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTab, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane mainTab;
    private ticas.ncrtes.estimation.EstimationUI panEstimation;
    private ticas.ncrtes.snowroute.SNRouteConfigPanel sNRouteConfigPanel2;
    private ticas.ncrtes.targetstation.TargetStationUI targetLaneUI1;
    // End of variables declaration//GEN-END:variables


}
