/*
 * Copyright (C) 2018 NATSRL @ UMD (University Minnesota Duluth)
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package admin.snowmgmt.truckroute;

import common.pyticas.HttpResult;
import admin.TeTRESConfig;
import admin.api.SnowRouteClient;
import admin.types.AbstractDataChangeListener;
import admin.types.SnowRouteInfo;
import java.awt.Frame;
import javax.swing.JOptionPane;

/**
 *
 * @author Chongmyung Park
 */
public class SNRouteEditDialog extends javax.swing.JDialog {

    private SnowRouteInfo sri;
    public String route_name;
    private SnowRouteClient model;

    public SNRouteEditDialog(Frame parent, SnowRouteInfo sri) {
        super(parent, true);
        initComponents();
        init(sri);
    }

    /**
     * initialize UI
     *
     * @param sri snow route information to edit
     */
    private void init(SnowRouteInfo sri) {
        this.sri = sri;
        this.model = new SnowRouteClient();
        this.route_name = sri.name;
        this.tbxRouteDesc.setText(sri.description);
        this.tbxRouteName.setText(sri.name);
        this.tbxProjectId.setText(sri.prj_id);

        this.model.addChangeListener(new AbstractDataChangeListener<SnowRouteInfo>() {
            @Override
            public void updateFailed(HttpResult result, SnowRouteInfo obj) {
                JOptionPane.showMessageDialog(TeTRESConfig.mainFrame, String.format("Fail to save route (%s)", result.res_msg));
            }

            @Override
            public void updateSuccess(int id) {
                dispose();
            }
        });
    }

    /**
     * *
     * update snow route information
     */
    private void updateRoute() {
        String name = this.tbxRouteName.getText();
        String desc = this.tbxRouteDesc.getText();
        String prj_id = this.tbxProjectId.getText();
        if (!checkName(name)) {
            return;
        }
        SnowRouteInfo ttriToUpdate = this.sri.clone();
        ttriToUpdate.name = name;
        ttriToUpdate.description = desc;
        ttriToUpdate.prj_id = prj_id;
        this.model.update(this.sri, ttriToUpdate);
    }

    /**
     * check if route name is valid
     *
     * @param name route name
     * @return true if route name is valid, else false
     */
    private boolean checkName(String name) {
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(TeTRESConfig.mainFrame, "Route name is required");
            return false;
        }
        if (name.length() > 100) {
            JOptionPane.showMessageDialog(TeTRESConfig.mainFrame, "Route name is too long. (100 characters limit)");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tbxRouteName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tbxProjectId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbxRouteDesc = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit");

        jLabel2.setText("Name");

        jLabel4.setText("Truck Route ID (optional)");

        jLabel3.setText("Description (optional)");

        tbxRouteDesc.setColumns(20);
        tbxRouteDesc.setRows(5);
        jScrollPane1.setViewportView(tbxRouteDesc);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbxRouteName, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(tbxProjectId, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbxRouteName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbxProjectId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        updateRoute();
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tbxProjectId;
    private javax.swing.JTextArea tbxRouteDesc;
    private javax.swing.JTextField tbxRouteName;
    // End of variables declaration

}
