/*
 * Copyright (C) 2018 NATSRL @ UMD (University Minnesota Duluth)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ticas.tetres.user.panels.operatingconditions;

import ticas.tetres.user.TeTRESConfig;
import ticas.tetres.user.types.OperatingConditionsInfo;
import ticas.common.util.FileHelper;
import javax.swing.JOptionPane;

/**
 *
 * @author "Chongmyung Park <chongmyung.park@gmail.com>"
 */
public class OperatingConditionEditDialog extends javax.swing.JDialog {

    private OperatingConditionsInfo exOperatingConditionsInfo;

    /**
     * Creates new form OperatingConditionsEditDialog
     */
    public OperatingConditionEditDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Creates new form OperatingConditionsEditDialog
     */
    public OperatingConditionEditDialog(OperatingConditionsInfo oci, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.init(oci);
    }

    private void init(OperatingConditionsInfo oci) {
        if(oci == null) {
            return;
        }
        this.exOperatingConditionsInfo = oci;
        this.tbxOperationConditionsName.setText(this.exOperatingConditionsInfo.name);
    }

    private void saveOrUpdate() {
        String name = this.tbxOperationConditionsName.getText();
        String desc = this.tbxDescription.getText();
        if(name.isEmpty() || !FileHelper.isFilenameValid(name)) {
            JOptionPane.showMessageDialog(TeTRESConfig.mainFrame, "Invalid Name");
            return;
        }
        // new
        if(this.exOperatingConditionsInfo == null) {
            if(OperatingConditionInfoHelper.exists(name)) {
                JOptionPane.showMessageDialog(TeTRESConfig.mainFrame, "Use other name. This name is already used.");
                return;
            }
            OperatingConditionsInfo oci = new OperatingConditionsInfo(name, desc);
            OperatingConditionInfoHelper.save(oci);
            OperatingConditionInfoHelper.loadOperatingConditionList();
            this.dispose();

        } else { // update
            String oldName = this.exOperatingConditionsInfo.name;
            if(oldName.equals(name)) {
                this.dispose();
            }
            if(OperatingConditionInfoHelper.exists(name)) {
                JOptionPane.showMessageDialog(TeTRESConfig.mainFrame, "Use other name. This name is already used.");
                return;
            }
            this.exOperatingConditionsInfo.name = name;
            boolean isUpdated = OperatingConditionInfoHelper.update(this.exOperatingConditionsInfo, oldName);
            if(isUpdated) {
                OperatingConditionInfoHelper.loadOperatingConditionList();
                this.dispose();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tbxOperationConditionsName = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbxDescription = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Operating Conditions Edit Dialog");

        jLabel1.setText("Name");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel2.setText("Description");

        tbxDescription.setColumns(20);
        tbxDescription.setRows(5);
        jScrollPane1.setViewportView(tbxDescription);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(btnCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addComponent(tbxOperationConditionsName)
                    .addComponent(btnOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tbxOperationConditionsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOK)
                            .addComponent(btnCancel))
                        .addGap(7, 7, 7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(45, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        this.saveOrUpdate();
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tbxDescription;
    private javax.swing.JTextField tbxOperationConditionsName;
    // End of variables declaration//GEN-END:variables


}
