/*
 * Copyright (C) 2018 NATSRL @ UMD (University Minnesota Duluth)
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ticas.tetres.user.panels.operatingconditions;

import ticas.common.ui.IInitializable;

/**
 *
 * @author "Chongmyung Park <chongmyung.park@gmail.com>"
 */
public class PanelOperatingConditions extends javax.swing.JPanel implements IInitializable {

    /**
     * Creates new form PanelOperatingConditions
     */
    public PanelOperatingConditions() {
        initComponents();
    }

    @Override
    public void init() {
        this.panelOperatingConditionConfig.init();
        this.panelOCParameters.init();
    }

    @Override
    public void refresh() {
        this.panelOperatingConditionConfig.refresh();
        this.panelOCParameters.refresh();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabOperationConditions = new javax.swing.JTabbedPane();
        panelOperatingConditionConfig = new ticas.tetres.user.panels.operatingconditions.PanelOperatingConditionConfig();
        panelOCParameters = new ticas.tetres.user.panels.operatingconditions.PanelOCParameters();

        tabOperationConditions.addTab("Operating Conditions", panelOperatingConditionConfig);
        tabOperationConditions.addTab("Parameters", panelOCParameters);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabOperationConditions, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabOperationConditions)
        );
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ticas.tetres.user.panels.operatingconditions.PanelOCParameters panelOCParameters;
    private ticas.tetres.user.panels.operatingconditions.PanelOperatingConditionConfig panelOperatingConditionConfig;
    private javax.swing.JTabbedPane tabOperationConditions;
    // End of variables declaration//GEN-END:variables
}
