/*
 * Copyright (C) 2018 NATSRL @ UMD (University Minnesota Duluth)
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package admin.snowmgmt;

import javax.swing.JPanel;
import common.ui.IInitializable;

/**
 *
 * @author Chongmyung Park <chongmyung.park@gmail.com>
 */
public class SnowMgmtPanel extends JPanel implements IInitializable {

    /**
     * Creates new form SpecialEventPanel
     */
    public SnowMgmtPanel() {
        initComponents();
    }

    @Override
    public void init() {
        this.tabMgmt.init();
        this.tabSnowRoute.init();
    }

    @Override
    public void refresh() {
        this.tabMgmt.refresh();
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabMgmt = new SNListPanel();
        tabSnowRoute = new admin.snowmgmt.truckroute.SNRouteListPanel();

        jTabbedPane1.addTab("Road Condition Info", tabMgmt);
        jTabbedPane1.addTab("Truck Route", tabSnowRoute);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// Variables declaration - do not modify
    private javax.swing.JTabbedPane jTabbedPane1;
    private SNListPanel tabMgmt;
    private admin.snowmgmt.truckroute.SNRouteListPanel tabSnowRoute;
    // End of variables declaration


}
