/*
 * Copyright (C) 2018 NATSRL @ UMD (University Minnesota Duluth)
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ticas.common.route;

import java.awt.EventQueue;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chongmyung Park
 */
public class RouteEditorPanel extends javax.swing.JPanel {

    /**
     * Creates new form RouteEditorPanel
     */
    public RouteEditorPanel() {
        initComponents();       
    }
    
    public void init() {        
        this.panRouteList.init();
        this.panRouteCreation.init();        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        asyncRequestAdapter1 = new org.jdesktop.http.async.event.AsyncRequestAdapter();
        tabMainTab = new javax.swing.JTabbedPane();
        panRouteList = new ticas.common.route.RouteListPanel();
        panRouteCreation = new ticas.common.route.RouteCreationPanel();

        tabMainTab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabMainTabStateChanged(evt);
            }
        });
        tabMainTab.addTab("Route List", panRouteList);
        tabMainTab.addTab("Create Route", panRouteCreation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabMainTab, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabMainTab, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabMainTab.getAccessibleContext().setAccessibleName("Freeway Route List");
    }// </editor-fold>//GEN-END:initComponents

        private void tabMainTabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabMainTabStateChanged
            //this.loadSectionList();
        }//GEN-LAST:event_tabMainTabStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.http.async.event.AsyncRequestAdapter asyncRequestAdapter1;
    private ticas.common.route.RouteCreationPanel panRouteCreation;
    private ticas.common.route.RouteListPanel panRouteList;
    private javax.swing.JTabbedPane tabMainTab;
    // End of variables declaration//GEN-END:variables


}
