/*
 * Copyright (C) 2018 NATSRL @ UMD (University Minnesota Duluth)
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ncrtes;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.prefs.Preferences;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author chong
 */
public class RegionConfig extends javax.swing.JDialog {

    private static Preferences prefs;

    static private final List<String> DEFAULT_REGIONS = Arrays.asList("Central", "Northeast", "Northwest", "South");
    static private final List<String> DEFAULT_TRUCK_STATIONS = Arrays.asList("ARDEN HILLS", "CAMDEN", "CEDAR AVENUE", "MARYLAND", "FOREST LAKE", "NORTH BRANCH", 
            "OAKDALE", "SPRING LAKE PARK", "ANOKA", "EDEN PRAIRIE", "GOLDEN VALLEY", "MAPLE GROVE", "PLYMOUTH", "HASTINGS", "JORDAN", "LAKEVILLE", 
            "MENDOTA HEIGHTS", "SHAKOPEE");
    private final DefaultListModel regionModel;
    private final DefaultListModel stationModel;
    
    private final static String REGION = "region";
    private final static String TRUCK_STATION = "truck_station";
    
    private static boolean initialized = false;
    /**
     * Creates new form RegionConfigDialog
     */
    public RegionConfig(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();    
        
        this.regionModel = new DefaultListModel();
        for(String region : getRegions()) {
            this.regionModel.addElement(region);
        }
        this.stationModel = new DefaultListModel();        
        for(String station : getTruckStations()) {
            this.stationModel.addElement(station);
        }        
        this.lstRegions.setModel(this.regionModel);
        this.lstTruckStations.setModel(this.stationModel);
        
        init();
    }
    
    public static void init() {
        if(!initialized)
            prefs = Preferences.userRoot().node("ncrtes.regions_stations");        
    }
    
    private List<String> modelToList(DefaultListModel model)
    {
        List<String> lst = new ArrayList<String>();
        for(Object v : model.toArray())
        {
            lst.add(v.toString());
        }
        return lst;
    }
    private void update() {
        prefs.put(TRUCK_STATION, listToString(modelToList(this.stationModel)));
        prefs.put(REGION, listToString(modelToList(this.regionModel)));
    }
    
    public static String listToString(List<String> arr) {
        return arr.toString().replaceAll("\\[|\\]", "").replaceAll(", ", ",");
    }
    
    public static List<String> stringToList(String str) {
        return Arrays.asList(str.split(","));
    }    
    
    public static List<String> getTruckStations() {
        init();
        return stringToList(prefs.get(TRUCK_STATION, listToString(DEFAULT_TRUCK_STATIONS)));
    }

    public static void setTruckStations(String stations) {
        init();
        prefs.put(TRUCK_STATION, stations);
    }

    public static List<String> getRegions() {
        init();
        return stringToList(prefs.get(REGION, listToString(DEFAULT_REGIONS)));
    }

    public static void setRegions(String regions) {
        init();
        prefs.put(REGION, regions);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAddRegion = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstTruckStations = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstRegions = new javax.swing.JList<>();
        btnDeleteRegion = new javax.swing.JButton();
        btnDeleteTruckStation = new javax.swing.JButton();
        btnAddTruckStation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Region Setting");

        jLabel1.setText("Regions");

        jLabel2.setText("Sub-Regions");

        btnAddRegion.setText("Add");
        btnAddRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRegionActionPerformed(evt);
            }
        });

        lstTruckStations.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane3.setViewportView(lstTruckStations);

        lstRegions.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane4.setViewportView(lstRegions);

        btnDeleteRegion.setText("Delete");
        btnDeleteRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRegionActionPerformed(evt);
            }
        });

        btnDeleteTruckStation.setText("Delete");
        btnDeleteTruckStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTruckStationActionPerformed(evt);
            }
        });

        btnAddTruckStation.setText("Add");
        btnAddTruckStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTruckStationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnDeleteRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAddRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnDeleteTruckStation, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAddTruckStation, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddRegion)
                    .addComponent(btnDeleteRegion))
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddTruckStation)
                    .addComponent(btnDeleteTruckStation))
                .addContainerGap())
        );

        pack();
    }private void btnAddRegionActionPerformed(java.awt.event.ActionEvent evt) {
        String region = JOptionPane.showInputDialog("Enter a New Region Name :");
        if(!region.isEmpty()) {
            this.regionModel.addElement(region);
            this.update();
        }
    }

    private void btnAddTruckStationActionPerformed(java.awt.event.ActionEvent evt) {
        String station = JOptionPane.showInputDialog("Enter a New Truck Station Name :");
        if(!station.isEmpty()) {
            this.stationModel.addElement(station);
            this.update();
        }
    }

    private void btnDeleteRegionActionPerformed(java.awt.event.ActionEvent evt) {
        int slt = this.lstRegions.getSelectedIndex();
        if(slt > 0) {
            this.regionModel.remove(slt);
            this.update();
        } else {
            JOptionPane.showMessageDialog(this, "Please select item to delete");
        }
    }

    private void btnDeleteTruckStationActionPerformed(java.awt.event.ActionEvent evt) {
        int slt = this.lstTruckStations.getSelectedIndex();
        if(slt > 0) {
            this.stationModel.remove(slt);
            this.update();
        } else {
            JOptionPane.showMessageDialog(this, "Please select item to delete");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegionConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegionConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegionConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegionConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }



        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegionConfig dialog = new RegionConfig(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnAddRegion;
    private javax.swing.JButton btnAddTruckStation;
    private javax.swing.JButton btnDeleteRegion;
    private javax.swing.JButton btnDeleteTruckStation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> lstRegions;
    private javax.swing.JList<String> lstTruckStations;
    // End of variables declaration
}
